### ISSUE TITLE
watertreatment : glitchy printer when spamming switch

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#830]
You can break the water analyser's printer by spamming the right button a couple of time while the printer light is still red. The paper will jump back and forth as a result.
![20161024213143_1](https://cloud.githubusercontent.com/assets/15633807/19660831/ad4d8166-9a31-11e6-81f1-e4fee4bd17d1.jpg)

**Comment by Zuntti** [comment]
Fixed.

**Comment by aleksijuvani** [comment]
Still happens. I think you need to open and close the lid once first.

**Comment by Zuntti** [comment]
Fixed.
